version: '3.8'

# Simplified Docker Compose for local development
# Runs only PostgreSQL + Redis - apps run natively for faster development

services:
  # PostgreSQL Database with TimescaleDB
  postgres:
    image: timescale/timescaledb:latest-pg15
    container_name: coinsphere-postgres
    environment:
      POSTGRES_USER: coinsphere
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: coinsphere_dev
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/prisma/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U coinsphere']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - coinsphere-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: coinsphere-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - coinsphere-network

  # Adminer (Database GUI)
  adminer:
    image: adminer:latest
    container_name: coinsphere-adminer
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    networks:
      - coinsphere-network

volumes:
  postgres_data:
  redis_data:

networks:
  coinsphere-network:
    driver: bridge
