version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: timescale/timescaledb:latest-pg15
    container_name: cryptosense-postgres
    environment:
      POSTGRES_USER: cryptosense
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cryptosense_dev
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U cryptosense']
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: cryptosense-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cryptosense-backend
    environment:
      NODE_ENV: development
      PORT: 3001
      DATABASE_URL: postgresql://cryptosense:password@postgres:5432/cryptosense_dev
      REDIS_URL: redis://redis:6379
      JWT_SECRET: dev-secret-key-change-in-production-min-32-chars
    ports:
      - '3001:3001'
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: npm run dev

  # ML Service
  ml-service:
    build:
      context: ./ml-service
      dockerfile: Dockerfile
    container_name: cryptosense-ml
    environment:
      DATABASE_URL: postgresql://cryptosense:password@postgres:5432/cryptosense_dev
      MODEL_VERSION: v1.0.0
      TRAINING_BATCH_SIZE: 32
    ports:
      - '8000:8000'
    volumes:
      - ./ml-service:/app
      - ml_models:/app/models
    depends_on:
      postgres:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend (Development)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: cryptosense-frontend
    environment:
      VITE_API_BASE_URL: http://localhost:3001/api/v1
      VITE_WS_URL: ws://localhost:3001
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: npm run dev

  # Adminer (Database GUI)
  adminer:
    image: adminer:latest
    container_name: cryptosense-adminer
    ports:
      - '8080:8080'
    depends_on:
      - postgres

volumes:
  postgres_data:
  redis_data:
  ml_models:

networks:
  default:
    name: cryptosense-network
