# BMad Core Configuration for Coinsphere
# Project: Crypto Portfolio Tracker with AI Predictions

project:
  name: Coinsphere
  description: AI-powered crypto portfolio tracker with market predictions and risk scoring
  version: 0.1.0
  domain: Cryptocurrency, FinTech, Portfolio Analytics

agents:
  - id: bmad-orchestrator
    name: BMad Orchestrator
    file: agents/bmad-orchestrator.md
    active: true
    description: Master coordinator for workflows and agent management

  - id: crypto-architect
    name: Crypto Architect
    file: agents/crypto-architect.md
    active: true
    description: Principal crypto systems architect for reliability, security, and correctness

tech-stack:
  backend:
    runtime: Node.js 20
    framework: Express
    language: TypeScript
    orm: Prisma
    databases:
      - PostgreSQL 15
      - TimescaleDB (time-series)
      - Redis 7 (caching, rate limiting)

  frontend:
    framework: React 18
    language: TypeScript
    bundler: Vite
    styling: Tailwind CSS
    components: Shadcn/ui
    charts: Recharts

  ml-pipeline:
    runtime: Python 3.11
    framework: FastAPI
    ml-libs:
      - PyTorch 2.0
      - scikit-learn
    models:
      - LSTM (price prediction)
      - Risk scoring algorithm

  infrastructure:
    cloud: AWS
    compute: ECS (containers)
    database: RDS (PostgreSQL)
    cache: ElastiCache (Redis)
    cicd: GitHub Actions
    monitoring: Sentry APM

security:
  authentication:
    - JWT tokens
    - TOTP 2FA (otplib)
    - Bcrypt password hashing

  protection:
    - Helmet.js (security headers)
    - CSRF tokens
    - Rate limiting (express-rate-limit)
    - Input sanitization (XSS prevention)
    - Audit logging

  encryption:
    - AES-256-GCM (TOTP secrets)
    - TLS/HTTPS in production

development:
  current-phase: P2 Implementation (Core Services)

  completed:
    - P0: Critical security issues (11/11)
    - P1: High-priority features (17/17)
    - Portfolio Service with analytics
    - Holdings Service with PnL tracking
    - Audit logging system
    - TOTP 2FA implementation

  in-progress:
    - Transactions Service
    - ML prediction integration
    - Degen Risk Score calculation

  upcoming:
    - Alert system
    - Advanced analytics
    - Multi-exchange integration
    - On-chain wallet tracking

coding-standards:
  - TypeScript strict mode enabled
  - ESLint + Prettier for code formatting
  - No floats for monetary calculations (use Decimal)
  - All timestamps in UTC
  - Comprehensive error handling with correlation IDs
  - Audit logging for security-sensitive operations
  - Input validation with Zod schemas
  - No silent failures - fail fast and loud

architecture-principles:
  - Event-driven design for real-time data
  - Idempotency for all state mutations
  - Graceful degradation on service failures
  - Circuit breakers for external APIs
  - Rate limiting awareness (CoinGecko: 50 calls/min)
  - WebSocket reconnection with message replay
  - Database query optimization (<100ms target)
  - Redis keys always have TTL
  - SLO-driven design (p95 latency <250ms)

data-integrity:
  - Cost-basis algorithms: FIFO, LIFO, HIFO
  - PnL includes fees, slippage, funding
  - Time-series data in TimescaleDB hypertables
  - Deduplication for all ingested data
  - Late event handling for out-of-order data
  - Transaction-level consistency for portfolio updates

workflows:
  # Future: Add custom workflows for Coinsphere development

bmad-version: 4.43.0
last-updated: 2025-10-08
